### ISSUE TITLE
can work in Ubuntu 22.04?

### ISSUE THREAD

**Issue by ykaljshsh** [dantmnf/zenbook-s14-linux#1]
How to install these drivers in ubuntu?

**Comment by dantmnf** [comment]
I'm not sure if there is prebuilt 6.12 (rc) kernel for Ubuntu, you may need to build the kernel yourself.

Or just wait for 6.12 kernel lands [Ubuntu release cycle](https://ubuntu.com/about/release-cycle).

**Comment by ykaljshsh** [comment]
> I'm not sure if there is prebuilt 6.12 (rc) kernel for Ubuntu, you may need to build the kernel yourself.
> 
> Or just wait for 6.12 kernel lands [Ubuntu release cycle](https://ubuntu.com/about/release-cycle).

Thanks : ）
